### ISSUE TITLE
How to collect the line coverage?

### ISSUE THREAD

**Issue by Lillian-jia** [ise-uiuc/TitanFuzz#3]
I am a student currently studying this project, and I am using coverage.py to collect line coverage data. However, the results I obtained are quite different from those in the paper, which has left me feeling confused.

**Comment by Lillian-jia** [comment]
> I am a student currently studying this project, and I am using coverage.py to collect line coverage data. However, the results I obtained are quite different from those in the paper, which has left me feeling confused.

I do like this:
coverage run --parallel-mode ./seed_program/torch.abs.py
coverage run --parallel-mode ./seed_program/torch.absolute.py
coverage run --parallel-mode ./seed_program/torch.acos.py
coverage run --parallel-mode ./seed_program/torch.acosh.py
coverage run --parallel-mode ./seed_program/torch.add.py
coverage run --parallel-mode ./seed_program/torch.addcdiv.py
coverage run --parallel-mode ./seed_program/torch.addcmul.py
coverage combine
coverage report

**Comment by clpoz** [comment]
Same questions, have you solved this? The mycoverage contents that authors provided seems can't collect the line coverage well, could you share your method?

**Comment by Lillian-jia** [comment]
> Same questions, have you solved this? The mycoverage contents that authors provided seems can't collect the line coverage well, could you share your method?

I think you can add --include=/path/to/torch when using coverage.py.

**Comment by clpoz** [comment]
that's very greatful your response, another confusion is that the project's ev_generation.py didn't provide coverage data, so do we must use coverage.py to calculate this by myself?

**Comment by Lillian-jia** [comment]
> that's very greatful your response, another confusion is that the project's ev_generation.py didn't provide coverage data, so do we must use coverage.py to calculate this by myself?

I think so.

**Comment by Lillian-jia** [comment]
> > Same questions, have you solved this? The mycoverage contents that authors provided seems can't collect the line coverage well, could you share your method?
> 
> I think you can add --include=/path/to/torch when using coverage.py.

Sorry I made a mistake. The command should be "python -m coverage run -L -a --source={torch_path} {file_path}".
